version: '3.8'

services:
  yoruverse-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: yoruverse-ui
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4321/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - yoruverse-network

networks:
  yoruverse-network:
    driver: bridge